films/urls.py
# -*- coding: utf-8 -*-
# Copyright 2018 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import url, include
from django.views.generic.edit import CreateView
from .views import films
from .views.films import SurveyCreateView, SurveyThanksCreateView
from .views.films import filmfor, surveypost
from .models import Survey

urlpatterns = [
#    url(r'^teams$', ideas.teamlist, name='teamlist'),
    url (r'^$', SurveyCreateView.as_view(success_url = 'survey'), \
                           name="submitsurvey"),
    url (r'^survey$', SurveyThanksCreateView.as_view(success_url = 'survey'), \
                               name="thanks"),
    url(r'^filmfor$', filmfor, name='apifilmfor'),
    url(r'^surveypost$', surveypost, name='apisurvey'),
]

hacks/urls.py
# -*- coding: utf-8 -*-
# Copyright 2016 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""hacks URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from ideas.views import rootindex
import ideas
import films

urlpatterns = [
    url(r'^$', rootindex.page, name='rootindex'),
    url(r'^ideas/', include('ideas.urls', namespace='hackideas')),
    url(r'^films/', include('films.urls', namespace='films')),     
    url(r'^hacksadmin/', admin.site.urls),
]

ideas/urls.py
# -*- coding: utf-8 -*-
# Copyright 2016 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import url, include
from django.views.generic.edit import CreateView
from .views import ideas
from .views.ideas import TeamListView, TeamCreateView
from .views.ideas import TeamMemberListView, TeamMemberCreateView
from .views.ideas import TeamIdeaListView, TeamIdeaCreateView, TeamIdeaUpdateView
from .views.ideas import TeamSubsListView, TeamSubsCreateView, TeamSubmissionUpdateView
from .views.ideas import AllIdeasListView
from .views import judge

from .models import Team


urlpatterns = [
#    url(r'^teams$', ideas.teamlist, name='teamlist'),
    url(r'^judge$', judge.judge, name='judge'),
    url(r'^judgelogin$', judge.judgelogin, name='judgelogin'),
    url(r'^judgelogout$', judge.judgelogout, name='judgelogout'),
    url(r'^teams$', TeamListView.as_view(), name='teamlist'),
    url (r'^create_team$', TeamCreateView.as_view(success_url = 'teams'), \
                           name="registerteam"),

    url(r'^teammembers$', TeamMemberListView.as_view(), name='teammemberlist'),
    url (r'^create_teammember$', TeamMemberCreateView.as_view(success_url = 'teammembers'), \
                           name="registerteammember"),

    url(r'^teamideas$', TeamIdeaListView.as_view(), name='teamidealist'),
    url(r'^tutti$', AllIdeasListView.as_view(), name='allidealist'),

    url (r'^create_teamidea$', TeamIdeaCreateView.as_view(success_url = 'teamideas'), \
                           name="registerteamidea"),


	  url (r'^editteamidea_(?P<pk>\d+)$', \
		         TeamIdeaUpdateView.as_view(success_url="teamideas"), \
		         name="editteamidea"),

    url(r'^teamsubmissions$', TeamSubsListView.as_view(), name='teamsubmissionlist'),

    url (r'^create_teamsubmission$', TeamSubsCreateView.as_view(success_url = 'teamsubmissions'), \
                           name="registerteamsubmission"),


    url (r'^editteamsubmission_(?P<pk>\d+)$', \
             TeamSubmissionUpdateView.as_view(success_url="teamsubmissions"), \
             name="editteamsubmission"),

]

ideas/models.py
# -*- coding: utf-8 -*-
# Copyright 2016 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.db import models

# Create your models here.

class Hackathon(models.Model):
  location = models.CharField(max_length=100,  verbose_name="Location")
  event = models.CharField(max_length=100,  verbose_name="Event")
  event_date = models.DateField(verbose_name="Event date")
  active = models.BooleanField(verbose_name="Submissions are active")
  def __str__(self):
    return self.event


class Team(models.Model):
  hackathon = models.ForeignKey(Hackathon, default=1)
  name = models.CharField(max_length=100,  verbose_name="Team name")
  def __str__(self):
    return self.name

class TeamMember(models.Model):
  team = models.ForeignKey(Team)
  twitterID = models.CharField(max_length=50, verbose_name="Twitter ID")
  emailID = models.EmailField(verbose_name="Email", null=True, default=None)
  tell_me = models.BooleanField(verbose_name="Watson can tell me about me",default=False)
  def __str__(self):
    return self.twitterID

class TeamIdea(models.Model):
  team = models.ForeignKey(Team)
  idea = models.TextField(verbose_name="Team Idea")
  flow = models.TextField(verbose_name="Process Flow")
  data = models.TextField(verbose_name="Data Source")
  conversation = models.BooleanField(verbose_name="Conversation", default=False)
  discovery = models.BooleanField(verbose_name="Discovery", default=False)
  languageTranslation = models.BooleanField(verbose_name="Language Translation")
  naturalLanguageClassifier = models.BooleanField(verbose_name="Natural Language Classifier")
  nlu = models.BooleanField(verbose_name="Natural Language Understanding", default=False)
  personalityInsights = models.BooleanField(verbose_name="Personality Insights")
  speechText = models.BooleanField(verbose_name="Speech to Text")
  textSpeech = models.BooleanField(verbose_name="Text to Speech")
  toneAnalyser = models.BooleanField(verbose_name="Tone Analyser")
  visualRecognition = models.BooleanField(verbose_name="Visual Recognition")

  def __str__(self):
    return self.idea


class TeamSubmission(models.Model):
  team = models.ForeignKey(Team)
  url = models.URLField(verbose_name="Application URL")
  gallery = models.BooleanField(verbose_name="App Gallery Interest", default=False)
  def __str__(self):
    return self.url

ideas/views/ideas.py
# -*- coding: utf-8 -*-
# Copyright 2016 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.shortcuts import render
from django import forms
from django.http import HttpResponse
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from ideas.models import Team, TeamMember, TeamIdea, Hackathon, TeamSubmission

import json

import logging
logger = logging.getLogger(__name__)


class TeamListView(generic.ListView):
  template_name = 'ideas/teamlist.html'
  model = Team
  context_object_name = 'teamlist'


class TeamForm(forms.ModelForm):
  hackathon = forms.ModelChoiceField(queryset=Hackathon.objects.filter(active=True))
  class Meta:
    model = Team
    fields = ['hackathon', 'name']


class TeamCreateView(generic.CreateView):
  template_name = 'ideas/registerteam.html'
  model = Team
  form_class = TeamForm


class TeamMemberListView(generic.ListView):
  template_name = 'ideas/teammemberlist.html'
  model = TeamMember
  context_object_name = 'teammemberlist'

  def get_queryset(self):
    return TeamMember.objects.order_by('team')

class TeamMemberForm(forms.ModelForm):
  team = forms.ModelChoiceField(queryset=Team.objects.filter(hackathon__active=True))
  class Meta:
    model = TeamMember
    fields = ['team', 'twitterID', 'emailID']

class TeamMemberCreateView(generic.CreateView):
  template_name = 'ideas/registerteammember.html'
  model = TeamMember
  form_class = TeamMemberForm

class TeamIdeaListView(generic.ListView):
  template_name = 'ideas/teamidealist.html'
  model = TeamIdea
  context_object_name = 'teamidealist'

  def get_queryset(self):
    return TeamIdea.objects.order_by('team__name')

class AllIdeasListView(generic.ListView):
  template_name = 'ideas/allidealist.html'
  model = TeamIdea
  context_object_name = 'teamidealist'
  paginate_by = 10

  def get_queryset(self):
    return TeamIdea.objects.order_by('team__hackathon__event','team__name')

class TeamIdeaForm(forms.ModelForm):
  team = forms.ModelChoiceField(queryset=Team.objects.filter(hackathon__active=True))
  class Meta:
    model = TeamIdea
    fields = ['team', 'idea',  'flow', 'data', \
            'nlu',  \
            'conversation', 'languageTranslation', \
            'naturalLanguageClassifier', 'personalityInsights', \
            'toneAnalyser', \
            'speechText', 'textSpeech',  \
            'visualRecognition', 'discovery' ]

  def clean(self):
    ts = self.cleaned_data["team"];
    t = Team.objects.filter(name=ts)[:1].get()
    activeEvent = t.hackathon.active

    if not activeEvent:
      msg = "The {0} hackathon at {1} has been archived, and no registrations are allowed".format(
                                                                                        t.hackathon.event,
                                                                                        t.hackathon.location)
      raise forms.ValidationError(msg)

    return super(TeamIdeaForm, self).clean()

class TeamIdeaCreateView(generic.CreateView):
  template_name = 'ideas/registerteamidea.html'
  model = TeamIdea
  form_class = TeamIdeaForm


class TeamIdeaUpdateForm(forms.ModelForm):
  class Meta:
    model = TeamIdea
    fields = ['team', 'idea',  'flow', 'data', \
            'nlu',  \
            'conversation', 'languageTranslation', \
            'naturalLanguageClassifier', 'personalityInsights', \
            'toneAnalyser', \
            'speechText', 'textSpeech',  \
            'visualRecognition', 'discovery' ]

  def clean(self):
    ts = self.cleaned_data["team"];
    t = Team.objects.filter(name=ts)[:1].get()
    activeEvent = t.hackathon.active

    if not activeEvent:
      msg = "The {0} hackathon at {1} has been archived, and no updates are allowed".format(
                                                                                        t.hackathon.event,
                                                                                        t.hackathon.location)
      raise forms.ValidationError(msg)

    return super(TeamIdeaUpdateForm, self).clean()

class TeamIdeaUpdateView(generic.UpdateView):
  template_name = 'ideas/editteamidea.html'
  model = TeamIdea
  form_class = TeamIdeaUpdateForm

  def get_context_data(self, **kwargs):
    context = super(TeamIdeaUpdateView, self).get_context_data(**kwargs)
    t = self.object.team
    s = TeamSubmission.objects.filter(team = t)
    context['submissions'] = s
    return context


class TeamSubsListView(generic.ListView):
  template_name = 'ideas/teamsubmissionlist.html'
  model = TeamSubmission
  context_object_name = 'teamsubmissionlist'

  def get_queryset(self):
    return TeamSubmission.objects.order_by('team__name')

class TeamSubsForm(forms.ModelForm):
  team = forms.ModelChoiceField(queryset=Team.objects.filter(hackathon__active=True))
  class Meta:
    model = TeamSubmission
    fields = ['team', 'url', 'gallery']


class TeamSubsCreateView(generic.CreateView):
  template_name = 'ideas/registerteamsubmission.html'
  model = TeamSubmission
  form_class = TeamSubsForm

class TeamSubmissionUpdateView(generic.UpdateView):
  template_name = 'ideas/editteamsubmission.html'
  model = TeamSubmission
  fields = ['team', 'url', 'gallery']

ideas/views/judge.py
# -*- coding: utf-8 -*-
# Copyright 2016 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django import forms
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

class FormLogin(forms.Form):
  username = forms.CharField(label = 'ID')
  password = forms.CharField(label = 'Key', widget = forms.PasswordInput)

  def clean(self):
    cleanedData = super(FormLogin, self).clean()
    username = cleanedData.get('username')
    password = cleanedData.get('password')
    if not authenticate(username=username, password=password):
      raise forms.ValidationError('Incorrect ID / Key combination')
    return cleanedData

def judgelogin(request):
  if request.POST:
    form = FormLogin(request.POST)
    if form.is_valid():
      username = form.cleaned_data["username"]
      password = form.cleaned_data["password"]
      user = authenticate(username=username, password=password)
      if user:
        login(request, user)
        if request.GET.get('next') is not None:
          return redirect(request.GET['next'])
  else:
    form = FormLogin()
  return render(request, 'judges/login.html', {'form': form})

def judgelogout(request):
  logout(request)
  return redirect('hackideas:judge')

@login_required
def judge(request):
  return render(request, 'judges/judge.html')

ideas/views/rootindex.py
# -*- coding: utf-8 -*-
# Copyright 2016 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.shortcuts import render

def page(request):
  return render(request, 'ideas/rootindex.html')

ideas/templates/ideas/allidealist.html
<!--
   Copyright 2016 IBM Corp. All Rights Reserved.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->

{% extends "ideas/base.html" %}

{% block title_html %}
  Hackathon Ideas
{% endblock %}


{% block core_body %}
  {% if teamidealist %}
    <div>Hackathon Ideas</div>
    <table class='table'>
    {% for idea in teamidealist %}

        <tr>
          <td>{{ idea.team.hackathon.event }}</td>
          <td><a href="{% url 'hackideas:editteamidea' idea.id %}">{{ idea.team }}</a></td>
          <td>{{ idea.idea }}</td>
        </tr>

    {% endfor %}
    </table>

    {% if is_paginated %}
      <ul class="pagination">
        {% for i in page_obj.paginator.page_range %}
          {% if i == page_obj.number %}
            <li class="active">
          {% else %}
            <li>
          {% endif %}
            <a href="{% url 'hackideas:allidealist' %}?page={{ i }}"> {{ i }}</a>
          </li>
        {% endfor %}
      </ul>
    {% endif %}

  {% else %}
    <p>No registered Team Ideas.</p>
  {% endif %}


{% endblock %}

ideas/templates/ideas/base.html
<!--
# Copyright 2016 IBM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
-->
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
	  {% block title_html %} {% endblock %}
	</title>
	{% load staticfiles %}
	<link rel="stylesheet"
        type="text/css"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'rootindex'%}">Home</a></li>
            <li><a href="{% url 'hackideas:teamlist'%}">Teams</a></li>
            <li><a href="{% url 'hackideas:teammemberlist'%}">Members</a></li>
            <li><a href="{% url 'hackideas:teamidealist'%}">Ideas</a></li>
            <li><a href="{% url 'hackideas:teamsubmissionlist'%}">Submissions</a></li>
            {% if user.is_authenticated %}
              <li><a href="{% url 'hackideas:judgelogout'%}">Log Out</a></li>
            {% else %}
              <li><a href="{% url 'hackideas:judge'%}">Judges</a></li> 	
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
        <h1>
	      Hackathon Teams - {% block h1 %} {% endblock %}
	    </h1>
        <div class="errorstatus" id="id_errormessagefromserver">{{ error }}</div>

		<div id="no-script"class="bg-info">This application needs JavaScript enabled in your browser!</div>

		<corebody>
		  {% block core_body %} {% endblock %}
		</corebody>
		<pagination>
		  {% if is_paginated %}
			<span>
			  {% if page_obj.has_previous %}
				{% block pagination_prev %} {% endblock %}
			  {% endif %}
			  <span style="margin-left:15px;margin-right:15px;">
				Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
			  </span>
			  {% if page_obj.has_next %}
				{% block pagination_next %} {% endblock %}
			  {% endif %}
			</span>
		  {% endif %}
		</pagination>

	  </div>
    </div>

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	  <script type="text/javascript" src="/static/js/services.js"></script>

	{% block script_extras %} {% endblock %}

  </body>
</html>

ideas/templates/ideas/registerteam.html
<!--
   Copyright 2016 IBM Corp. All Rights Reserved.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->  

{% extends "ideas/base.html" %}

{% block title_html %}
  Hackathon Team Registration 
{% endblock %}


{% block core_body %}
  <p>Register new team</p>
    <form method="post" action="{% url 'hackideas:registerteam' %}" >
        {% csrf_token %} 
        <!-- This line inserts a CSRF token. -->
        <table>
            {{ form.as_table }}
            <!-- This line displays lines of the form. -->
        </table>
        <p><input type="submit" value="Register" /></p>
    </form>
{% endblock %}

ideas/templates/ideas/rootindex.html
<!--
   Copyright 2016 IBM Corp. All Rights Reserved.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->  

{% extends "ideas/base.html" %}

{% block title_html %}
  Application Root Index 
{% endblock %}


{% block core_body %}
  <p>Application pages are:</p>
  <ul>
     <li> <a href="{% url 'hackideas:teamlist'%}">Teams</a> </li>
     <li> <a href="{% url 'hackideas:registerteam'%}">Register team</a> </li> 
     <li> <a href="{% url 'hackideas:teammemberlist'%}">Team Members</a> </li>
     <li> <a href="{% url 'hackideas:registerteammember'%}">Register team member</a> </li> 
     <li> <a href="{% url 'hackideas:teamidealist'%}">Team Ideas</a> </li>
     <li> <a href="{% url 'hackideas:registerteamidea'%}">Register team idea</a> </li> 
     <li> <a href="{% url 'hackideas:registerteamsubmission'%}">Register team submission</a> </li>      
  </ul>
{% endblock %}

ideas/templates/ideas/teamidealist.html
<!--
   Copyright 2016 IBM Corp. All Rights Reserved.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->  

{% extends "ideas/base.html" %}

{% block title_html %}
  Hackathon Ideas 
{% endblock %}


{% block core_body %}
  {% if teamidealist %}
    <div>Hackathon Ideas</div>
    <table class='table'>
    {% for idea in teamidealist %}
      {% if idea.team.hackathon.active%}
        <tr>
          <td>{{ idea.team.hackathon.event }}</td> 
          <td><a href="{% url 'hackideas:editteamidea' idea.id %}">{{ idea.team }}</a></td> 
          <td>{{ idea.idea }}</td>
        </tr>  
      {% endif %}
    {% endfor %}
    </table>
  {% else %}
    <p>No registered Team Ideas.</p>
  {% endif %}

<div>
   <a href="{% url 'hackideas:registerteamidea' %}">Register Team Idea</a><br />
</div>  

{% endblock %}

ideas/templates/ideas/teamsubmissionlist.html
<!--
   Copyright 2016 IBM Corp. All Rights Reserved.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->  

{% extends "ideas/base.html" %}

{% block title_html %}
  Hackathon Submissions 
{% endblock %}


{% block core_body %}
  {% if teamsubmissionlist %}
    <div>Hackathon Ideas</div>
    <table class='table'>
      <thead>
        <tr>  
          <th>Hackathon</th> 
          <th>Team</th> 
          <th>Application URL</th> 
          <th>Interest in hosting on IBM Watson Gallery</th>           
        <tr>
      </thead>        
    {% for sub in teamsubmissionlist %}
      {% if sub.team.hackathon.active%}
        <tr>
          <td>{{ sub.team.hackathon.event }}</td> 
          <td><a href="{% url 'hackideas:editteamsubmission' sub.id %}">{{ sub.team }}</a></td>          
          <td>{{ sub.url }}</td>
          <td>{{ sub.gallery }}</td>
        </tr>  
      {% endif %}
    {% endfor %}
    </table>
  {% else %}
    <p>No registered Team Submissions.</p>
  {% endif %}

<div>
   <a href="{% url 'hackideas:registerteamsubmission' %}">Register Team Submission</a><br />
</div>  

{% endblock %}